services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=eventifydatabase
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
